### ISSUE TITLE
Compile issues with Shibboleth block

### ISSUE THREAD

**Issue by chrisreichley** [hannonhill/Custom-Authentication-Module-Examples#5]
ShibbAuthentication.java:25: error: class CascadeShibAuth is public, should be declared in a file named CascadeShibAuth.java
public class CascadeShibAuth implements Authenticator
       ^
ShibbAuthentication.java:68: error: method log in class CascadeShibAuth cannot be applied to given types;
                log("Redirecting to custom logout URL: ", LOGOUT_URL);
                ^
  required: String
  found: String,String
  reason: actual and formal argument lists differ in length
2 errors

**Comment by chrisreichley** [comment]
This happens when I grab the latest git version and attempt to compile.

Any advice?

**Comment by rgriffith** [comment]
@chrisreichley As [you mentioned in Slack](https://hannonhill-users.slack.com/archives/C2J3FSQMD/p1655219845994089), it does appear the issue is the file name needs to be updated to reflect the class name and the usage of the logging method needs to be tweaked. We'll work on pushing out a fix soon for these items.

That being said, it is worth mentioning if you are planning to upgrade to 8.20, the Log4j dependency will need to be updated due to the upgrade to Log4j2. The logging dependency was updated to reflect this in the latest commit.

**Comment by rgriffith** [comment]
@chrisreichley I just pushed a commit that should resolve the issues you are encountering when compiling. When you have a moment, can you try again and let me know if you continue to run into issues?
